export const styles = {
    sideBarTouchable: {
        margin: 5,
        marginTop: 50,
        padding: 10,
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row',
        borderWidth: 2,
        borderRadius: 15,
        borderColor: 'rgba(0,0,0,0.1)',
    },
    sideBarTouchableDisabled: {
        margin: 5,
        marginTop: 50,
        padding: 10,
        display: 'flex',
        justifyContent: 'flex-start',
        alignItems: 'center',
        flexDirection: 'row',
        backgroundColor: 'rgba(0,0,0,0.1)',
        borderWidth: 2,
        borderRadius: 15,
        borderColor: 'rgba(0,0,0,0.1)',
        opacity: 0.5,
    },
    layerContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 10,
        borderWidth: 1,
        borderRadius: 5,
        margin: 5,
    },
    sideBarText: {
        fontSize: 20,
        width: '100%',
        paddingLeft: 10,
        marginRight: 20,
    },
    sideBarWrapper: {
        display: 'flex',
        flexDirection: 'column',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        display: 'flex',
    },
    modalContent: {
        width: '70%',
        padding: 20,
        borderRadius: 10,
        backgroundColor: 'white',
        alignItems: 'center',
    },
    modalTouchable: {
        padding: 10,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: 'rgba(0,0,0,0.1)',
        backgroundColor: 'rgba(0,0,0,0.05)',
        paddingHorizontal: 20,
    },
    buttonRow: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        gap: 30,
    },
    mapView: {
        width: "100%",
        height: "100%"
    },
    circleButton: {
        width: 60,
        height: 60,
        borderRadius: 60,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#fff',
    },
    pencilButton: {
        backgroundColor: 'white',
        bottom: 30,
        right: 30,
    },
    recordButton: {
        backgroundColor: 'white',
        bottom: 110,
        right: 30,
        display: 'flex',
        position: 'absolute',
    },
    drawCircleButton: {
        backgroundColor: 'white',
        bottom: 190,
        right: 30,
        display: 'flex',
        position: 'absolute',
    },
    drawPolygonButton: {
        backgroundColor: 'white',
        bottom: 270,
        right: 30,
        display: 'flex',
        position: 'absolute',
    },
    colorPickerButton: {
        backgroundColor: 'white',
        bottom: 30,
        left: 30,
        display: 'flex',
        position: 'absolute',
    },
    garbageButton: {
        backgroundColor: 'white',
        bottom: 110,
        left: 30,
        display: 'flex',
        position: 'absolute',
    },
    eraserButton: {
        backgroundColor: 'white',
        bottom: 350,
        right: 30,
        display: 'flex',
        position: 'absolute',
    },
}